// Code generated by openapi-transformer. DO NOT EDIT.

#[path = "downtimes.rs"]
pub mod downtimes;

use anyhow::Result;

use crate::config::Config;

/// All spec-generated pup commands.
///
/// Re-run the generator to add or remove tags; pup never needs manual changes
/// for new commands.
#[derive(clap::Subcommand)]
pub enum GeneratedCommand {
    /// Manage downtimes resources
    Downtimes {
        #[command(subcommand)]
        action: downtimes::Command,
    },
}

pub async fn run(cfg: &Config, command: GeneratedCommand) -> Result<()> {
    match command {
        GeneratedCommand::Downtimes { action } => downtimes::run(cfg, action).await,
    }
}
