// Code generated by openapi-transformer. DO NOT EDIT.

use anyhow::Result;

use crate::config::Config;

/// All spec-generated pup commands.
///
/// Re-run the generator to add or remove tags; pup never needs manual changes
/// for new commands.
#[derive(clap::Subcommand)]
pub enum GeneratedCommand {}

pub async fn run(cfg: &Config, command: GeneratedCommand) -> Result<()> {
    match command {}
}
